Importing essential libraries

In [7]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn as skl
import pandas as pd

From the libraries import essential funtions

In [8]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score

Below code lets us see all the rows in our dataset

In [9]:
pd.set_option('display.max_rows', None)

Import csv file in notebook

In [10]:
hou = pd.read_csv(r"Chennai houseing sale.csv"
                 ,sep = ",")
hou = hou.fillna(0)
hou.head()

PRT_ID        AREA  INT_SQFT   DATE_SALE  DIST_MAINROAD  N_BEDROOM  \
0  P03210  Karapakkam      1004  04-05-2011            131        1.0   
1  P09411  Anna Nagar      1986  19-12-2006             26        2.0   
2  P01812       Adyar       909  04-02-2012             70        1.0   
3  P05346   Velachery      1855  13-03-2010             14        3.0   
4  P06210  Karapakkam      1226  05-10-2009             84        1.0   

   N_BATHROOM  N_ROOM SALE_COND PARK_FACIL  ... UTILITY_AVAIL  STREET MZZONE  \
0         1.0       3  AbNormal        Yes  ...        AllPub   Paved      A   
1         1.0       5  AbNormal         No  ...        AllPub  Gravel     RH   
2         1.0       3  AbNormal        Yes  ...           ELO  Gravel     RL   
3         2.0       5    Family         No  ...       NoSewr    Paved      I   
4         1.0       3  AbNormal        Yes  ...        AllPub  Gravel      C   

  QS_ROOMS QS_BATHROOM  QS_BEDROOM  QS_OVERALL  REG_FEE  COMMIS  SALES_PRICE  
0      4.0         3.9         4.9       4.330   380000  144400      7600000  
1      4.9         4.2         2.5       3.765   760122  304049     21717770  
2      4.1         3.8         2.2       3.090   421094   92114     13159200  
3      4.7         3.9         3.6       4.010   356321   77042      9630290  
4      3.0         2.5         4.1       3.290   237000   74063      7406250  

[5 rows x 22 columns]

Delete the duplicate entries

In [11]:
hou = hou.drop_duplicates()
hou.head()

PRT_ID        AREA  INT_SQFT   DATE_SALE  DIST_MAINROAD  N_BEDROOM  \
0  P03210  Karapakkam      1004  04-05-2011            131        1.0   
1  P09411  Anna Nagar      1986  19-12-2006             26        2.0   
2  P01812       Adyar       909  04-02-2012             70        1.0   
3  P05346   Velachery      1855  13-03-2010             14        3.0   
4  P06210  Karapakkam      1226  05-10-2009             84        1.0   

   N_BATHROOM  N_ROOM SALE_COND PARK_FACIL  ... UTILITY_AVAIL  STREET MZZONE  \
0         1.0       3  AbNormal        Yes  ...        AllPub   Paved      A   
1         1.0       5  AbNormal         No  ...        AllPub  Gravel     RH   
2         1.0       3  AbNormal        Yes  ...           ELO  Gravel     RL   
3         2.0       5    Family         No  ...       NoSewr    Paved      I   
4         1.0       3  AbNormal        Yes  ...        AllPub  Gravel      C   

  QS_ROOMS QS_BATHROOM  QS_BEDROOM  QS_OVERALL  REG_FEE  COMMIS  SALES_PRICE  
0      4.0         3.9         4.9       4.330   380000  144400      7600000  
1      4.9         4.2         2.5       3.765   760122  304049     21717770  
2      4.1         3.8         2.2       3.090   421094   92114     13159200  
3      4.7         3.9         3.6       4.010   356321   77042      9630290  
4      3.0         2.5         4.1       3.290   237000   74063      7406250  

[5 rows x 22 columns]

Dropping the fields which have text in them

In [12]:
X_train = hou.drop(["PRT_ID", "AREA", "DATE_SALE","SALE_COND", "PARK_FACIL","UTILITY_AVAIL",
                    "STREET","SALES_PRICE","MZZONE","BUILDTYPE","DATE_BUILD"]
                   , axis = 1)
X_train.head()

INT_SQFT  DIST_MAINROAD  N_BEDROOM  N_BATHROOM  N_ROOM  QS_ROOMS  \
0      1004            131        1.0         1.0       3       4.0   
1      1986             26        2.0         1.0       5       4.9   
2       909             70        1.0         1.0       3       4.1   
3      1855             14        3.0         2.0       5       4.7   
4      1226             84        1.0         1.0       3       3.0   

   QS_BATHROOM  QS_BEDROOM  QS_OVERALL  REG_FEE  COMMIS  
0          3.9         4.9       4.330   380000  144400  
1          4.2         2.5       3.765   760122  304049  
2          3.8         2.2       3.090   421094   92114  
3          3.9         3.6       4.010   356321   77042  
4          2.5         4.1       3.290   237000   74063

Writting the output coloum in the y train matrix( A different way than above)

In [13]:
y_train = hou.drop(hou.columns[:21], axis = 1)
y_train.head()

SALES_PRICE
0      7600000
1     21717770
2     13159200
3      9630290
4      7406250

Printing shape and converting the data type to int

In [14]:
X_train = np.array(X_train)

print(np.shape(X_train))
X_train = X_train.astype('int64')
print(X_train.dtype)
print(X_train[:5])

(7109, 11)
int64
[[  1004    131      1      1      3      4      3      4      4 380000
  144400]
 [  1986     26      2      1      5      4      4      2      3 760122
  304049]
 [   909     70      1      1      3      4      3      2      3 421094
   92114]
 [  1855     14      3      2      5      4      3      3      4 356321
   77042]
 [  1226     84      1      1      3      3      2      4      3 237000
   74063]]


Printing the shape and datatype

In [15]:
y_train = np.array(y_train)
print(y_train.shape)
print(y_train.dtype)
print(y_train[:5])

(7109, 1)
int64
[[ 7600000]
 [21717770]
 [13159200]
 [ 9630290]
 [ 7406250]]


Normalizing data using Z-score normalization

In [16]:
scaler = StandardScaler()
X_norm = scaler.fit_transform(X_train)
X_norm

array([[-0.82660819,  0.54699179, -0.79300115, ...,  1.55941054,
         0.02140121,  0.04309502],
       [ 1.32040901, -1.28230608,  0.45229268, ...,  0.02418695,
         2.67847103,  2.07006079],
       [-1.03431352, -0.51574316, -0.79300115, ...,  0.02418695,
         0.30865011, -0.62074837],
       ...,
       [ 0.50707866,  0.91285136,  0.45229268, ...,  0.02418695,
        -0.41649714,  0.3303889 ],
       [-1.30105089, -1.0383997 , -0.79300115, ...,  1.55941054,
         0.33839974, -0.27814901],
       [ 1.12363553,  0.9825389 ,  1.69758652, ...,  0.02418695,
        -0.19405295, -0.77693934]])

Assinging linear regression funtion

In [17]:
lr = LinearRegression()

Applying linear regression model to our data sets

In [18]:
lr.fit(X_train, y_train)

LinearRegression()

Bais, y intercept

In [19]:
b = lr.intercept_
b

array([724161.80061443])

Weight

In [20]:
w = lr.coef_
w

array([[-1.41719294e+03,  4.79275796e+02, -1.42750987e+06,
        -1.03825981e+06,  2.11234743e+06,  1.17298523e+04,
        -4.27505765e+04, -1.22034623e+04,  2.39019182e+04,
         1.94058188e+01,  4.47852983e+00]])

Prediction

In [21]:
y_predtrain = lr.predict(X_train)
y_predtrain

array([[11221730.17250096],
       [20626233.61967235],
       [11890930.98962811],
       ...,
       [ 9895542.51459062],
       [10140037.62861043],
       [ 9377954.66954183]])

In [22]:
print(y_predtrain.dtype)

float64


Converting all values in y_predtrain into int and printing the datatype

In [23]:
y_predtrain = y_predtrain.astype("int64")

In [24]:
print(y_predtrain.dtype)

int64


In [25]:
y = pd.DataFrame(y_predtrain)
y.head()

0
0  11221730
1  20626233
2  11890930
3   9542067
4   7801667

Checking r2 score

In [29]:
r2_score(y_train, y_predtrain)

0.8320036952542431

Doing a random test

In [30]:
test_1 = np.array([1004,131,1.0,1.0,3,4.0,3.9,4.9,4.330,380000,144400])
pred = np.dot(w, test_1) + b
rounded = np.round(pred,2)
print(rounded)

[11180159.17]


THANK YOU !